export const loadDataCenter = {
  REQUEST_DATA: 'REQUEST_DATA',
  RECEIVE_DATA: 'RECEIVE_DATA',
  RECEIVE_SUCCESS: 'RECEIVE_SUCCESS',
  RECEIVE_ERROR: 'RECEIVE_ERROR',
}

export const panel = {
  ADD_PANEL: 'ADD_PANEL'
}